version: '3.8'
services:
  nginx:
    container_name: sms-nginx
    image: nginx
    build:
      context: ./docker/nginx
    ports:
      - "80:80"

  mongo:
    container_name: sms-mongo
    image: mongo
    restart: always
    volumes: 
      - ./docker/data:/data/db

  backend:
    container_name: sms-be
    image: sms/be
    build: 
      context: .
    restart: always
    env_file: .env
    depends_on: 
      - sms-mongo
    links:
      - sms-mongo
      - sms-redis

  redis:
    container_name: sms-redis
    image: redis:alpine

volumes: 
  data: