version: '3.8'
services:
  nginx:
    container_name: sms-nginx
    image: nginx
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    networks:
      - nginx
      - backend
  mongo:
    container_name: sms-mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes: 
      - ./docker/data:/data/db
    networks:
      - backend
  backend:
    container_name: sms-be
    image: sms/be
    build: 
      context: .
    restart: always
    ports:
      - '3000:3000'
    env_file: .env
    depends_on: 
      - mongo
    links:
      - mongo
    networks:
      - backend

networks:
  nginx:
  backend:
volumes: 
  data: