export const ERROR_CODE = {
    BAD_REQUEST: 'BAD_REQUEST',
    NOT_FOUND: 'NOT_FOUND',
    UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
    DUPLICATE: 'DUPLICATE',
    TOKEN_INVALID: 'TOKEN_INVALID',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL: 'INTERNAL'
};
