export const TIMETABLE_REQUEST_TYPE = {
    OUT: 'OUT',
    ABSENT_ADD: 'ABSENT-ADD',
    ABSENT: 'ABSENT',
    LATE: 'LATE',
    SOON: 'SOON',
    ADD: 'ADD'
};
export const APPROVAL_STATUS = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
};
